// Common data types shared across all API clients and chart components

export interface DataPoint {
  date: string; // ISO date, fiscal year "2023-24", or label
  value: number | null;
  label?: string; // For categorical data (e.g., state name, sector)
}

export interface DataSeries {
  source: "worldbank" | "mospi" | "datagov" | "census" | "rbi" | "ppac" | "moafw" | "fci" | "imd";
  indicator: string; // Human-readable indicator name
  indicatorId?: string; // Machine-readable ID (e.g., "NY.GDP.MKTP.KD.ZG")
  unit: string; // e.g., "%" , "USD", "INR Crore", "Index"
  frequency: "annual" | "quarterly" | "monthly" | "daily";
  data: DataPoint[];
  /** Optional explicit line/marker color (CSS color string). When set, LineChart
   *  uses this instead of Plotly's automatic color cycle. Used by SeriesFilterChart
   *  to keep chip dot colors consistent with the chart lines even when some series
   *  are hidden and the filtered array changes positions. */
  color?: string;
  metadata: {
    lastUpdated: string;
    sourceUrl: string;
    notes?: string;
  };
}

export interface FilterOption {
  id: string | number;
  label: string;
}

export interface DatasetFilters {
  [key: string]: FilterOption[];
}

// API response status
export interface ApiResponse<T> {
  data: T | null;
  loading: boolean;
  error: string | null;
}

// MoSPI-specific types
export type MospiDataset =
  | "PLFS"
  | "CPI"
  | "IIP"
  | "ASI"
  | "NAS"
  | "WPI"
  | "ENERGY";

export interface MospiIndicator {
  code: number;
  name: string;
  unit?: string;
  viz?: string; // Suggested visualization type
}

// World Bank specific types
export interface WorldBankIndicatorMeta {
  id: string;
  name: string;
  sourceNote: string;
}

export interface WorldBankDataPoint {
  indicator: { id: string; value: string };
  country: { id: string; value: string };
  date: string;
  value: number | null;
}

// ─── Energy Sankey types ───────────────────────────────────────────────

/** Unit of energy measurement */
export type EnergyUnit = "KToE" | "PetaJoules";

/** Available fiscal years in the MoSPI Energy dataset (newest first) */
export const ENERGY_YEARS = [
  "2023-24",
  "2022-23",
  "2021-22",
  "2020-21",
  "2019-20",
  "2018-19",
  "2017-18",
  "2016-17",
  "2015-16",
  "2014-15",
  "2013-14",
  "2012-13",
] as const;

export type EnergyYear = (typeof ENERGY_YEARS)[number];

/** Raw row returned by MoSPI Energy Balance API */
export interface EnergyBalanceRow {
  year: string;
  commodity: string;
  commodityCode: number;
  sector: string;
  sectorCode: number;
  subSector?: string;
  subSectorCode?: number;
  value: number;
}

/** A node in the Sankey diagram */
export interface SankeyNode {
  id: string; // Unique machine key (e.g., "coal", "electricity_gen")
  label: string; // Display label (e.g., "Coal", "Electricity Generation")
  color: string; // RGBA color string
  column: number; // 0-based column for x positioning (0=source, 1=primary, 2=transform, 3=end-use)
}

/** A link (flow) in the Sankey diagram */
export interface SankeyLink {
  source: number; // Index into SankeyNode[]
  target: number; // Index into SankeyNode[]
  value: number; // Energy value in selected unit
  color: string; // RGBA color string (semi-transparent)
  label: string; // Hover label (e.g., "Coal → Industry: 200,947 KToE")
}

/** Complete data for rendering a Sankey diagram */
export interface SankeyData {
  nodes: SankeyNode[];
  links: SankeyLink[];
  unit: EnergyUnit;
  year: string;
  totalSupply: number;
  totalConsumption: number;
}

// ─── IIP (Index of Industrial Production) — Monthly types ──────────────

/** A single category's index + growth for one month */
export interface IIPCategoryPoint {
  index: number | null;
  growth: number | null;
}

/** A single month's IIP data across all categories */
export interface IIPMonthDataPoint {
  year: number;
  month: string;   // Full month name e.g. "January"
  label: string;   // Short label e.g. "Jan 2025"
  date: string;    // "YYYY-MM" for chart x-axis
  // Sectoral
  general: IIPCategoryPoint;
  mining: IIPCategoryPoint;
  manufacturing: IIPCategoryPoint;
  electricity: IIPCategoryPoint;
  // Use-based
  primaryGoods: IIPCategoryPoint;
  capitalGoods: IIPCategoryPoint;
  intermediateGoods: IIPCategoryPoint;
  infraGoods: IIPCategoryPoint;
  consumerDurables: IIPCategoryPoint;
  consumerNonDurables: IIPCategoryPoint;
}

/** Complete IIP monthly dataset (generated by scripts/generate-iip-monthly.mjs) */
export interface IIPMonthlyData {
  baseYear: string;
  lastUpdated: string;
  source: string;
  sourceUrl: string;
  notes: string;
  monthly: IIPMonthDataPoint[];
}

// ─── IIP (Index of Industrial Production) — Annual types ───────────────

/** Available IIP fiscal years (newest first) */
export const IIP_YEARS = [
  "2024-25",
  "2023-24",
  "2022-23",
  "2021-22",
  "2020-21",
  "2019-20",
  "2018-19",
  "2017-18",
  "2016-17",
  "2015-16",
  "2014-15",
  "2013-14",
  "2012-13",
] as const;

export type IIPYear = (typeof IIP_YEARS)[number];

/** IIP category data point — parallel arrays aligned with `years` */
export interface IIPCategoryData {
  index: number[]; // Index values for each year
  growth: number[]; // Growth rate (%) for each year
}

/** Complete IIP annual dataset (loaded from static JSON) */
export interface IIPAnnualData {
  baseYear: string;
  lastUpdated: string;
  years: string[];
  sectoral: Record<string, IIPCategoryData>;
  useBased: Record<string, IIPCategoryData>;
}

// ─── PLFS (Periodic Labour Force Survey) types ─────────────────────────

/** Gender breakdown: male, female, person (total) */
export interface PLFSGenderData {
  male: number[];
  female: number[];
  person: number[];
}

/** Unemployment rate with additional rural/urban breakdown */
export interface PLFSUnemploymentData extends PLFSGenderData {
  rural: number[];
  urban: number[];
}

/** Complete PLFS annual dataset (loaded from static JSON) */
export interface PLFSAnnualData {
  lastUpdated: string;
  notes: string;
  years: string[];
  lfpr: PLFSGenderData;
  wpr: PLFSGenderData;
  ur: PLFSUnemploymentData;
}

// ---------------------------------------------------------------------------
// RBI Key Rates types
// ---------------------------------------------------------------------------

/** RBI key policy rates and reserve requirements (annual end-of-year, static JSON) */
export interface RBIKeyRatesData {
  lastUpdated: string;
  notes: string;
  years: string[];
  repoRate: (number | null)[];
  reverseRepoSDF: (number | null)[];
  crr: (number | null)[];
  slr: (number | null)[];
}

// ---------------------------------------------------------------------------
// RBI Policy Rates — event-level (new higher-frequency format)
// ---------------------------------------------------------------------------

/** A single rate-change event (date + new value) */
export interface RBIRateEvent {
  date: string;  // "YYYY-MM-DD"
  value: number;
}

/** Event-level policy rate decisions (generated by scripts/generate-rbi.mjs) */
export interface RBIPolicyRatesData {
  lastUpdated: string;
  notes: string;
  repoRate: RBIRateEvent[];
  reverseRepoSDF: RBIRateEvent[];
  crr: RBIRateEvent[];
  slr: RBIRateEvent[];
}

// ---------------------------------------------------------------------------
// RBI Forex Reserves — monthly
// ---------------------------------------------------------------------------

export interface RBIForexDataPoint {
  date: string;   // "YYYY-MM"
  value: number;  // USD billion
}

export interface RBIForexData {
  lastUpdated: string;
  unit: string;
  notes: string;
  monthly: RBIForexDataPoint[];
}

// ---------------------------------------------------------------------------
// NAS (National Accounts Statistics) — Quarterly GDP types
// ---------------------------------------------------------------------------

/** A single quarter's GDP data from MoSPI NAS */
export interface NASQuarterDataPoint {
  year: string;       // Fiscal year, e.g. "2024-25"
  quarter: string;    // "Q1" | "Q2" | "Q3" | "Q4"
  label: string;      // Human-readable, e.g. "2024-25 Q1"
  realGrowth: number | null;     // YoY real GDP growth rate (%)
  nominalGrowth: number | null;  // YoY nominal GDP growth rate (%)
  nominalGDP: number | null;     // GDP at current prices (₹ Crore)
  realGDP: number | null;        // GDP at constant 2011-12 prices (₹ Crore)
}

/** A single quarter's GVA sector data from MoSPI NAS */
export interface NASGVAQuarterDataPoint {
  year: string;
  quarter: string;
  label: string;
  // Broad sector aggregates (simple average of sub-sectors)
  agriculture: number | null;
  industry: number | null;
  services: number | null;
  // Sub-sectors
  mining: number | null;
  manufacturing: number | null;
  electricity: number | null;
  construction: number | null;
  tradeHotelsTransport: number | null;
  financialRealEstate: number | null;
  publicAdmin: number | null;
  totalGVA: number | null;
}

/** Complete NAS quarterly GVA by sector dataset (loaded from static JSON) */
export interface NASGVASectorData {
  lastUpdated: string;
  source: string;
  sourceUrl: string;
  baseYear: string;
  unit: string;
  notes: string;
  sectorLabels: Record<string, string>;
  quarters: NASGVAQuarterDataPoint[];
}

/** Complete NAS quarterly dataset (loaded from static JSON) */
export interface NASQuarterlyData {
  lastUpdated: string;
  source: string;
  sourceUrl: string;
  baseYear: string;
  unit: string;
  notes: string;
  quarters: NASQuarterDataPoint[];
}

// ---------------------------------------------------------------------------
// Petroleum / PPAC types
// ---------------------------------------------------------------------------

/** Supply-side petroleum data (crude oil and refined products, in KToE) */
export interface PetroleumSupply {
  /** Domestic crude oil production */
  crudeOilProduction: number[];
  /** Crude oil imports */
  crudeOilImports: number[];
  /** Total crude available for refining (production + imports) */
  refineryThroughput: number[];
  /** Refined product imports */
  oilProductImports: number[];
  /** Refined product exports (positive values) */
  oilProductExports: number[];
}

/** Consumption breakdown of petroleum products by type (in KToE) */
export interface PetroleumConsumption {
  diesel: number[];
  petrol: number[];
  lpg: number[];
  naphtha: number[];
  petCoke: number[];
  atf: number[];
  fuelOil: number[];
  kerosene: number[];
  bitumen: number[];
  lubricants: number[];
  others: number[];
}

/** Complete petroleum dataset (loaded from static JSON, sourced from MoSPI Energy) */
export interface PetroleumData {
  lastUpdated: string;
  unit: string;
  notes: string;
  years: string[];
  supply: PetroleumSupply;
  consumption: PetroleumConsumption;
}

// ---------------------------------------------------------------------------
// PLFS Quarterly types
// ---------------------------------------------------------------------------

/** Gender breakdown for a single sector (male / female / person total) */
export interface PLFSGenderValues {
  male: number | null;
  female: number | null;
  person: number | null;
}

/** One indicator's data split by sector for a single quarter */
export interface PLFSSectorValues {
  urban: PLFSGenderValues;
  /** null = not released for this quarter (urban-only bulletin) */
  rural: PLFSGenderValues | null;
  /** null = not released for this quarter */
  combined: PLFSGenderValues | null;
}

/** A single quarter's full snapshot (LFPR, WPR, UR) */
export interface PLFSQuarterPoint {
  year: string;       // Fiscal year, e.g. "2022-23"
  quarter: string;    // e.g. "APR-JUN" | "JUL-SEP" | "OCT-DEC" | "JAN-MAR"
  quarterNum: number; // 1=Q1 (APR-JUN) … 4=Q4 (JAN-MAR)
  date: string;       // "YYYY-MM" — start-month of the quarter for chart x-axis
  label: string;      // Human-readable, e.g. "Apr–Jun 2022"
  lfpr: PLFSSectorValues;
  wpr: PLFSSectorValues;
  ur: PLFSSectorValues;
}

/** Complete PLFS quarterly dataset (generated from MoSPI quarterly bulletin) */
export interface PLFSQuarterlyData {
  source: string;
  sourceUrl: string;
  lastUpdated: string;
  notes: string;
  quarters: PLFSQuarterPoint[];
}

// ---------------------------------------------------------------------------
// ASI (Annual Survey of Industries) — Annual types
// ---------------------------------------------------------------------------

/** One NIC-sector's data arrays, parallel to years[] */
export interface ASINICSector {
  nicCode: string;
  nicName: string;
  nicNameShort: string;
  gva: (number | null)[];          // ₹ lakhs
  workers: (number | null)[];      // count
  fixedCapital: (number | null)[]; // ₹ lakhs
  wages: (number | null)[];        // ₹ lakhs
}

/** All-India aggregate arrays, parallel to years[] */
export interface ASITotals {
  factories: number[];
  output: number[];       // ₹ lakhs
  gva: number[];          // ₹ lakhs
  fixedCapital: number[]; // ₹ lakhs
  workers: number[];
  personsEngaged: number[];
  maleWorkers: number[];
  femaleWorkers: number[];
  wages: number[];        // ₹ lakhs
}

/** Complete ASI annual dataset (generated from MoSPI ASI API) */
export interface ASIAnnualData {
  source: string;
  sourceUrl: string;
  lastUpdated: string;
  notes: string;
  years: string[];
  totals: ASITotals;
  byNIC: ASINICSector[];
}

// ---------------------------------------------------------------------------
// WPI (Wholesale Price Index) — Monthly types
// ---------------------------------------------------------------------------

/** A single month's WPI YoY % change data */
export interface WPIMonthDataPoint {
  year: number;
  month: string;
  label: string;                  // e.g. "Apr 2013"
  headline: number | null;        // Overall WPI
  primaryArticles: number | null; // Primary Articles
  fuelPower: number | null;       // Fuel & Power
  manufactured: number | null;    // Manufactured Products
  foodIndex: number | null;       // Food Index (WPI)
}

/** Complete WPI monthly dataset (loaded from static JSON) */
export interface WPIMonthlyData {
  lastUpdated: string;
  baseYear: string;   // "2011-12"
  source: string;
  sourceUrl: string;
  notes: string;
  monthly: WPIMonthDataPoint[];
}

// ---------------------------------------------------------------------------
// PLFS Wages & Worker Distribution (All India annual, from MoSPI PLFS API)
// ---------------------------------------------------------------------------

/** Male / Female / Person breakdown for a wage or earnings series */
export interface PLFSGenderWage {
  note: string;
  years: string[];
  person: number[];
  male:   number[];
  female: number[];
}

/** Worker distribution % by broad employment status */
export interface PLFSWorkerDistCategory {
  person: number[];
  male:   number[];
  female: number[];
}

export interface PLFSWorkerDist {
  note: string;
  years: string[];
  selfEmployed: PLFSWorkerDistCategory;
  regularWage:  PLFSWorkerDistCategory;
  casualLabour: PLFSWorkerDistCategory;
}

export interface PLFSWagesData {
  source: string;
  sourceUrl: string;
  lastUpdated: string;
  notes: string;
  years: string[];
  /** Average monthly wage from regular salaried employment (₹/month) */
  regularWages: PLFSGenderWage;
  /** Average daily wage from casual labour work (₹/day) */
  casualWages: PLFSGenderWage;
  /** Average gross earnings from self-employment in last 30 days (₹/month) */
  selfEmpEarnings: PLFSGenderWage;
  /** % distribution of workers by broad employment status */
  workerDist: PLFSWorkerDist;
}

// ---------------------------------------------------------------------------
// State-level PLFS data (generated from MoSPI PLFS annual API)
// ---------------------------------------------------------------------------

export interface PLFSStateSeries {
  stateName: string;      // API state name (e.g. "Andhra Pradesh")
  geoName: string;        // GeoJSON ST_NM match value (may differ for UTs)
  ur_person: (number | null)[];    // Unemployment Rate (person, combined), parallel to years[]
  lfpr_female: (number | null)[];  // Female LFPR (combined), parallel to years[]
  lfpr_male: (number | null)[];    // Male LFPR (combined), parallel to years[]
  lfpr_person: (number | null)[];  // Total LFPR (combined, all persons), parallel to years[]
}

export interface PLFSStateData {
  source: string;
  sourceUrl: string;
  lastUpdated: string;
  notes: string;
  years: string[];          // Fiscal years, e.g. ["2017-18", ..., "2023-24"]
  states: PLFSStateSeries[];
}

// ---------------------------------------------------------------------------
// State-level CPI data (generated from MoSPI CPI API)
// ---------------------------------------------------------------------------

export interface CPIStateSeries {
  stateName: string;
  geoName: string;
  inflation: (number | null)[]; // YoY % change (General/Combined), parallel to months[]
}

export interface CPIStateData {
  source: string;
  sourceUrl: string;
  lastUpdated: string;
  notes: string;
  months: string[];         // "YYYY-MM" labels, e.g. ["2024-01", ..., "2024-12"]
  states: CPIStateSeries[];
}

// ---------------------------------------------------------------------------
// State-level GSDP data (sourced from RBI Handbook of Statistics)
// ---------------------------------------------------------------------------

export interface GSDPStateSeries {
  stateName: string;
  geoName: string;
  /** Real GSDP in ₹ Crore at constant 2011-12 prices */
  gsdp_real_cr: (number | null)[];
  /** Nominal GSDP in ₹ Crore at current prices */
  gsdp_nominal_cr: (number | null)[];
  /** YoY growth rate (%) computed from real GSDP; null for first year */
  gsdp_growth: (number | null)[];
}

export interface GSDPStateData {
  source: string;
  sourceUrl: string;
  lastUpdated: string;
  notes: string;
  /** Fiscal year labels, e.g. ["2011-12", ..., "2024-25"] */
  years: string[];
  states: GSDPStateSeries[];
}

// ---------------------------------------------------------------------------
// Agriculture — Annual types
// ---------------------------------------------------------------------------

export interface AgricultureFoodgrain {
  notes: string;
  /** Total foodgrain production (Mt) */
  total: number[];
  /** Kharif season production (Mt) */
  kharif: number[];
  /** Rabi season production (Mt) */
  rabi: number[];
}

export interface AgricultureCrops {
  notes: string;
  rice: number[];
  wheat: number[];
  pulses: number[];
  coarseCereals: number[];
}

export interface AgricultureCropYield {
  notes: string;
  /** Rice yield (kg per hectare) */
  rice: number[];
  /** Wheat yield (kg per hectare) */
  wheat: number[];
}

export interface AgricultureHorticulture {
  notes: string;
  /** Total horticulture production including fruits, vegetables, spices, plantations (Mt) */
  total: number[];
  /** Fruits production (Mt) */
  fruits: number[];
  /** Vegetables production (Mt) */
  vegetables: number[];
}

export interface AgricultureFCIProcurement {
  notes: string;
  /** Rice procured by FCI + state agencies (Mt) */
  rice: number[];
  /** Wheat procured by FCI + state agencies (Mt) */
  wheat: number[];
}

export interface AgricultureMSP {
  notes: string;
  /** Rice MSP (₹ per quintal, Common/Grade A) */
  rice: number[];
  /** Wheat MSP (₹ per quintal) */
  wheat: number[];
}

export interface AgricultureFCIStocks {
  notes: string;
  rice: number[];
  wheat: number[];
  /** Mandatory minimum buffer norm for April 1 (rice + wheat combined, Mt) */
  bufferNorm: number;
}

export interface AgricultureMonsoon {
  notes: string;
  /** % departure from Long Period Average (LPA = 880.6 mm, Jun–Sep) */
  departure: number[];
}

export interface AgricultureData {
  source: string;
  sourceUrl: string;
  lastUpdated: string;
  notes: string;
  /** Fiscal years, e.g. ["2000-01", ..., "2024-25"] */
  years: string[];
  foodgrain: AgricultureFoodgrain;
  crops: AgricultureCrops;
  cropYield: AgricultureCropYield;
  msp: AgricultureMSP;
  fciStocks: AgricultureFCIStocks;
  fciProcurement: AgricultureFCIProcurement;
  horticulture: AgricultureHorticulture;
  monsoon: AgricultureMonsoon;
}

// ---------------------------------------------------------------------------
// RBI Banking & Credit — Annual types
// ---------------------------------------------------------------------------

/** GNPA (Gross Non-Performing Assets) data — available from 2011-12 onwards */
export interface RBIBankingGNPA {
  years: string[];
  /** GNPA as % of Gross Advances — all SCBs */
  ratio: number[];
  /** GNPA ratio for Public Sector Banks (PSBs) */
  psb: number[];
  /** GNPA ratio for Private Sector Banks */
  privateBanks: number[];
}

/** Credit outstanding split by bank group (₹ lakh crore, end-March) */
export interface RBIBankingCreditByType {
  notes: string;
  years: string[];
  /** Public Sector Banks credit (₹ lakh crore) */
  psb: number[];
  /** Private Sector Banks credit (₹ lakh crore) */
  privateBanks: number[];
}

/** Capital Adequacy (CRAR) — Basel III, % of Risk-Weighted Assets */
export interface RBIBankingCRAR {
  years: string[];
  allBanks: number[];
  psb: number[];
  privateBanks: number[];
}

/** Sectoral credit deployment as % of non-food credit — from 2011-12 onwards */
export interface RBIBankingSectoral {
  years: string[];
  agriculture: number[];
  industry: number[];
  services: number[];
  personalLoans: number[];
}

/** Complete RBI Banking & Credit annual dataset (static JSON from RBI DBIE / Handbook) */
export interface RBIBankingData {
  source: string;
  sourceUrl: string;
  lastUpdated: string;
  unit: string;
  notes: string;
  /** Fiscal years, e.g. ["2004-05", ..., "2024-25"] */
  years: string[];
  /** Non-food bank credit (₹ lakh crore, end of March) */
  credit: number[];
  /** Bank deposits (₹ lakh crore, end of March) */
  deposits: number[];
  /** YoY credit growth (%), null for first year */
  creditGrowth: (number | null)[];
  /** YoY deposit growth (%), null for first year */
  depositGrowth: (number | null)[];
  /** Credit-to-Deposit ratio (%) */
  cdRatio: number[];
  /** Bank credit as % of nominal GDP */
  creditToGDP: number[];
  gnpa: RBIBankingGNPA;
  sectoralCredit: RBIBankingSectoral;
  crar: RBIBankingCRAR;
  creditByBankType: RBIBankingCreditByType;
}

// ---------------------------------------------------------------------------
// CPI (Consumer Price Index) — Monthly types
// ---------------------------------------------------------------------------

/** A single month's CPI YoY % change data, All India Combined */
export interface CPIMonthDataPoint {
  year: number;
  month: string;
  label: string;                    // e.g. "Mar 2014"
  // Major groups
  general: number | null;           // Overall CPI (headline)
  foodBeverages: number | null;     // Food & Beverages
  fuelLight: number | null;         // Fuel & Light
  housing: number | null;           // Housing
  clothingFootwear: number | null;  // Clothing & Footwear
  miscellaneous: number | null;     // Miscellaneous
  // Food sub-groups
  cereals: number | null;
  pulses: number | null;
  oilsFats: number | null;
  milkProducts: number | null;
  meatFish: number | null;
  vegetables: number | null;
  fruits: number | null;
  spices: number | null;
}

/** Complete CPI monthly dataset (loaded from static JSON) */
export interface CPIMonthlyData {
  lastUpdated: string;
  baseYear: string;   // "2012"
  source: string;
  sourceUrl: string;
  notes: string;
  months: CPIMonthDataPoint[];
}
