import { useQuery } from "@tanstack/react-query";
import type { SankeyData, EnergyUnit } from "@/lib/api/types";

const BASE_PATH = "/india-data-dashboard";

/**
 * Build the static JSON URL for a given year/unit combination.
 * Files are pre-generated by scripts/generate-energy-data.mjs and committed to repo.
 */
function staticJsonUrl(year: string, unit: EnergyUnit): string {
  return `${BASE_PATH}/data/mospi/energy-sankey-${year}-${unit.toLowerCase()}.json`;
}

/**
 * Hook to load pre-fetched MoSPI Energy Balance Sankey data.
 *
 * All data is pre-generated at build time as static JSON files,
 * avoiding CORS issues with the MoSPI API (which blocks browser requests).
 */
export function useSankeyData(year: string, unit: EnergyUnit) {
  return useQuery<SankeyData>({
    queryKey: ["mospi", "energy", "sankey", year, unit],
    queryFn: async () => {
      const url = staticJsonUrl(year, unit);
      const response = await fetch(url);

      if (!response.ok) {
        throw new Error(
          `Energy data for ${year} (${unit}) is not available. ` +
            `Please rebuild the site to regenerate data files.`
        );
      }

      // Guard against HTML error pages disguised as 200 OK
      const text = await response.text();
      try {
        return JSON.parse(text) as SankeyData;
      } catch {
        throw new Error(
          `Energy data for ${year} (${unit}) returned an invalid format. ` +
            `The data file may not have been pre-generated.`
        );
      }
    },
    staleTime: Infinity, // Static data never goes stale within a deployment
    gcTime: 1000 * 60 * 60 * 24, // Keep in cache for 24 hours
    retry: 1,
  });
}
