import { useQuery } from "@tanstack/react-query";
import type { IIPAnnualData, IIPMonthlyData, IIPMonthDataPoint, DataSeries } from "@/lib/api/types";

const BASE_PATH = "/india-data-dashboard";

/**
 * Hook to load pre-fetched MoSPI IIP (Index of Industrial Production) data.
 *
 * All data is pre-generated as a static JSON file under public/data/mospi/,
 * avoiding CORS issues with the MoSPI API (which blocks browser requests).
 */
export function useIIPAnnualData() {
  return useQuery<IIPAnnualData>({
    queryKey: ["mospi", "iip", "annual"],
    queryFn: async () => {
      const url = `${BASE_PATH}/data/mospi/iip-annual.json`;
      const response = await fetch(url);

      if (!response.ok) {
        throw new Error("IIP data not available");
      }

      // Guard against HTML error pages disguised as 200 OK
      const text = await response.text();
      try {
        return JSON.parse(text) as IIPAnnualData;
      } catch {
        throw new Error("IIP data returned invalid format");
      }
    },
    staleTime: Infinity, // Static data never goes stale within a deployment
    gcTime: 1000 * 60 * 60 * 24, // Keep in cache for 24 hours
    retry: 1,
  });
}

/**
 * Convert IIP data into DataSeries[] for use with chart components.
 *
 * @param data       The full IIP annual dataset
 * @param group      "sectoral" or "useBased"
 * @param categories Array of category names to include (e.g., ["General", "Mining"])
 * @param metric     "index" for IIP index values, "growth" for YoY growth rates
 */
export function iipToSeries(
  data: IIPAnnualData,
  group: "sectoral" | "useBased",
  categories: string[],
  metric: "index" | "growth"
): DataSeries[] {
  const source = group === "sectoral" ? data.sectoral : data.useBased;

  return categories
    .map((cat) => {
      const catData = source[cat];
      if (!catData) return null;

      const values = metric === "index" ? catData.index : catData.growth;

      return {
        source: "mospi" as const,
        indicator: cat,
        indicatorId: `IIP_${group}_${cat}_${metric}`,
        unit: metric === "index" ? "Index" : "%",
        frequency: "annual" as const,
        data: data.years.map((year, i) => ({
          date: year,
          value: values[i] ?? null,
        })),
        metadata: {
          lastUpdated: data.lastUpdated,
          sourceUrl: "https://www.mospi.gov.in/",
          notes: `Base year: ${data.baseYear}`,
        },
      };
    })
    .filter(Boolean) as DataSeries[];
}

// ─── Monthly IIP ────────────────────────────────────────────────────────────

/**
 * Hook to load pre-fetched MoSPI IIP monthly data.
 *
 * Data is pre-generated by scripts/generate-iip-monthly.mjs and written to
 * public/data/mospi/iip-monthly.json (calendar year months, Jan 2012 → latest).
 */
export function useIIPMonthlyData() {
  return useQuery<IIPMonthlyData>({
    queryKey: ["mospi", "iip", "monthly"],
    queryFn: async () => {
      const url = `${BASE_PATH}/data/mospi/iip-monthly.json`;
      const response = await fetch(url);

      if (!response.ok) {
        throw new Error("IIP monthly data not available");
      }

      const text = await response.text();
      try {
        return JSON.parse(text) as IIPMonthlyData;
      } catch {
        throw new Error("IIP monthly data returned invalid format");
      }
    },
    staleTime: Infinity,
    gcTime: 1000 * 60 * 60 * 24,
    retry: 1,
  });
}

/**
 * Field keys on IIPMonthDataPoint that hold category data.
 */
type IIPMonthField = keyof Omit<
  IIPMonthDataPoint,
  "year" | "month" | "label" | "date"
>;

const MONTHLY_CATEGORY_META: Record<
  IIPMonthField,
  { label: string; group: "sectoral" | "useBased" }
> = {
  general:             { label: "General",                          group: "sectoral" },
  mining:              { label: "Mining",                           group: "sectoral" },
  manufacturing:       { label: "Manufacturing",                    group: "sectoral" },
  electricity:         { label: "Electricity",                      group: "sectoral" },
  primaryGoods:        { label: "Primary Goods",                    group: "useBased" },
  capitalGoods:        { label: "Capital Goods",                    group: "useBased" },
  intermediateGoods:   { label: "Intermediate Goods",               group: "useBased" },
  infraGoods:          { label: "Infrastructure/Construction Goods", group: "useBased" },
  consumerDurables:    { label: "Consumer Durables",                group: "useBased" },
  consumerNonDurables: { label: "Consumer Non-durables",            group: "useBased" },
};

/**
 * Convert IIP monthly data into DataSeries[] for chart components.
 *
 * @param data     The full IIP monthly dataset
 * @param fields   Which category fields to include (e.g. ["general", "mining"])
 * @param metric   "index" for raw IIP values, "growth" for YoY % change
 */
export function iipMonthlyToSeries(
  data: IIPMonthlyData,
  fields: IIPMonthField[],
  metric: "index" | "growth"
): DataSeries[] {
  return fields.map((field) => {
    const meta = MONTHLY_CATEGORY_META[field];
    return {
      source: "mospi" as const,
      indicator: meta.label,
      indicatorId: `IIP_monthly_${field}_${metric}`,
      unit: metric === "index" ? "Index (2011-12=100)" : "%",
      frequency: "monthly" as const,
      data: data.monthly.map((pt) => ({
        date: pt.date,       // "YYYY-MM" — Plotly handles this natively
        value: pt[field][metric],
      })),
      metadata: {
        lastUpdated: data.lastUpdated,
        sourceUrl: data.sourceUrl,
        notes: `${data.notes} Base year: ${data.baseYear}`,
      },
    };
  });
}

/** Re-export the field type so dashboard pages can use it without digging into types.ts */
export type { IIPMonthField };
